services:
  mysql:
    image: mysql:latest
    container_name: my-sql-default
    ports:
      - "3306:3306"
    network_mode: bridge
    environment:
        MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - ./db-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - ./db-scripts/mysql-data.sql:/docker-entrypoint-initdb.d/mysql-data.sql